# Site settings
title: Marco-7
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/marco7" # the subpath of your site, e.g. /blog/
url: "http://ericathegreat.github.io" # the base hostname & protocol for your site

# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: none
markdown: kramdown

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Marco-7

description: Mobile Apparatus for Reconnaisance, Collection and Organization
author:
  name: Erica The Great
  email: ericathegreat@gmail.com
  github: ericathegreat
  twitter: ericatgreat
  bio: Mobile Apparatus for Reconnaisance, Collection and Organization
  email_md5: ccae8bfc23eb471900a1583e15f6de77

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH: /sevendays
